"""update proposal queue

Revision ID: 2cdc65ba1a43
Revises: 82b68934a6e8
Create Date: 2026-01-09 23:53:29.718810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdc65ba1a43'
down_revision: Union[str, Sequence[str], None] = '82b68934a6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_proposals', sa.Column('proposal_type', sa.String(), nullable=False, default='article_merge'))
    op.add_column('merge_proposals', sa.Column('source_event_id', sa.UUID(), nullable=True))
    op.alter_column('merge_proposals', 'source_article_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_merge_pair'), 'merge_proposals', type_='unique')
    op.create_unique_constraint('uq_article_merge_pair', 'merge_proposals', ['source_article_id', 'target_event_id'])
    op.create_unique_constraint('uq_event_merge_pair', 'merge_proposals', ['source_event_id', 'target_event_id'])
    op.create_foreign_key(None, 'merge_proposals', 'news_events', ['source_event_id'], ['id'])
    op.add_column('news_events', sa.Column('merged_into_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'news_events', 'news_events', ['merged_into_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_events', type_='foreignkey')
    op.drop_column('news_events', 'merged_into_id')
    op.drop_constraint(None, 'merge_proposals', type_='foreignkey')
    op.drop_constraint('uq_event_merge_pair', 'merge_proposals', type_='unique')
    op.drop_constraint('uq_article_merge_pair', 'merge_proposals', type_='unique')
    op.create_unique_constraint(op.f('uq_merge_pair'), 'merge_proposals', ['source_article_id', 'target_event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('merge_proposals', 'source_article_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('merge_proposals', 'source_event_id')
    op.drop_column('merge_proposals', 'proposal_type')
    # ### end Alembic commands ###
