"""sources snapshot

Revision ID: 3aae31c6feda
Revises: 63564db8f769
Create Date: 2026-01-15 18:23:22.095146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aae31c6feda'
down_revision: Union[str, Sequence[str], None] = '63564db8f769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_events', sa.Column('sources_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_events', 'sources_snapshot')
    # ### end Alembic commands ###
