"""adjust event dates

Revision ID: 3dc85a408e21
Revises: 52ca3aacf903
Create Date: 2026-01-17 22:43:45.951878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dc85a408e21'
down_revision: Union[str, Sequence[str], None] = '52ca3aacf903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('articles', 'published_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('news_events', 'is_international',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_events', 'is_international',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('articles', 'published_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('articles', 'updated_at')
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
