"""ai impact

Revision ID: 4b1f3b27b247
Revises: 54ee44c8d76e
Create Date: 2026-01-13 16:51:26.310076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1f3b27b247'
down_revision: Union[str, Sequence[str], None] = '54ee44c8d76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_events', sa.Column('ai_impact_score', sa.Integer(), nullable=True))
    op.add_column('news_events', sa.Column('category_tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_news_events_article_count'), 'news_events', ['article_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_events_article_count'), table_name='news_events')
    op.drop_column('news_events', 'category_tag')
    op.drop_column('news_events', 'ai_impact_score')
    # ### end Alembic commands ###
