"""is_international

Revision ID: 52ca3aacf903
Revises: d8d3d5444428
Create Date: 2026-01-16 18:49:00.309195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52ca3aacf903'
down_revision: Union[str, Sequence[str], None] = 'd8d3d5444428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_events', sa.Column('is_international', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_news_events_is_international'), 'news_events', ['is_international'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_events_is_international'), table_name='news_events')
    op.drop_column('news_events', 'is_international')
    # ### end Alembic commands ###
