"""add_structured_interests

Revision ID: 6257a322aa9e
Revises: 0019d2284619
Create Date: 2026-01-08 14:44:39.517755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6257a322aa9e'
down_revision: Union[str, Sequence[str], None] = '0019d2284619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('news_events', sa.Column('interest_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('news_events', sa.Column('ownership_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('newspapers', sa.Column('ownership_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newspapers', 'ownership_type')
    op.drop_column('news_events', 'ownership_stats')
    op.drop_column('news_events', 'interest_counts')
    op.drop_column('articles', 'interests')
    # ### end Alembic commands ###
