"""publisher_isights

Revision ID: 63564db8f769
Revises: b97858db8177
Create Date: 2026-01-15 16:39:50.499034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63564db8f769'
down_revision: Union[str, Sequence[str], None] = 'b97858db8177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_events', sa.Column('publisher_isights', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_events', 'publisher_isights')
    # ### end Alembic commands ###
