"""stance to float

Revision ID: 82b68934a6e8
Revises: 6257a322aa9e
Create Date: 2026-01-08 15:20:40.092420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b68934a6e8'
down_revision: Union[str, Sequence[str], None] = '6257a322aa9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('stance', sa.Float(), nullable=True))
    op.drop_column('articles', 'stance_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('stance_label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'stance')
    # ### end Alembic commands ###
