"""empty message

Revision ID: 87e6dbd6ad6f
Revises: 5a80c4acb0ef
Create Date: 2026-01-12 13:44:34.165338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e6dbd6ad6f'
down_revision: Union[str, Sequence[str], None] = '5a80c4acb0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source_rank', sa.Integer(), nullable=True))
    op.add_column('feeds', sa.Column('url_pattern', sa.Text(), nullable=True))
    op.add_column('feeds', sa.Column('feed_type', sa.String(), server_default='sitemap', nullable=False))
    op.add_column('feeds', sa.Column('is_ranked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('feeds', sa.Column('use_browser_render', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('feeds', sa.Column('scroll_depth', sa.Integer(), server_default='1', nullable=False))
    op.add_column('news_events', sa.Column('hot_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('news_events', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('news_events', sa.Column('best_source_rank', sa.Integer(), nullable=True))
    op.add_column('news_events', sa.Column('first_article_date', sa.DateTime(), nullable=True))
    op.add_column('news_events', sa.Column('last_article_date', sa.DateTime(), nullable=True))
    op.add_column('news_events', sa.Column('editorial_score', sa.Float(), nullable=False, server_default='0.0'))
    op.create_index(op.f('ix_news_events_hot_score'), 'news_events', ['hot_score'], unique=False)
    op.create_index(op.f('ix_news_events_published_at'), 'news_events', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_events_published_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_hot_score'), table_name='news_events')
    op.drop_column('news_events', 'editorial_score')
    op.drop_column('news_events', 'last_article_date')
    op.drop_column('news_events', 'first_article_date')
    op.drop_column('news_events', 'best_source_rank')
    op.drop_column('news_events', 'published_at')
    op.drop_column('news_events', 'hot_score')
    op.drop_column('feeds', 'scroll_depth')
    op.drop_column('feeds', 'use_browser_render')
    op.drop_column('feeds', 'is_ranked')
    op.drop_column('feeds', 'feed_type')
    op.drop_column('feeds', 'url_pattern')
    op.drop_column('articles', 'source_rank')
    # ### end Alembic commands ###
