"""news job queue

Revision ID: 9d6d5450a0c7
Revises: 3dc85a408e21
Create Date: 2026-01-18 00:41:30.971902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6d5450a0c7'
down_revision: Union[str, Sequence[str], None] = '3dc85a408e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # update ArticlesQueueName enum
    op.execute("ALTER TYPE articlesqueuename ADD VALUE 'ANALYZE'")
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
