"""main topics agg

Revision ID: a1ab85f828b9
Revises: a0fc6794e716
Create Date: 2026-01-12 22:27:11.583044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1ab85f828b9'
down_revision: Union[str, Sequence[str], None] = 'a0fc6794e716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('news_events', sa.Column('main_topic_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_events', 'main_topic_counts')
