"""clickbait

Revision ID: a9eeabe4f389
Revises: 2cdc65ba1a43
Create Date: 2026-01-11 12:48:55.778635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9eeabe4f389'
down_revision: Union[str, Sequence[str], None] = '2cdc65ba1a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('clickbait_score', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('clickbait_reasoning', sa.Text(), nullable=True))
    op.alter_column('merge_proposals', 'proposal_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.add_column('news_events', sa.Column('clickbait_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('news_events', sa.Column('article_counts_by_bias', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_events', 'article_counts_by_bias')
    op.drop_column('news_events', 'clickbait_distribution')
    op.alter_column('merge_proposals', 'proposal_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'''article_merge'''::character varying"),
               existing_nullable=False)
    op.drop_column('articles', 'clickbait_reasoning')
    op.drop_column('articles', 'clickbait_score')
    # ### end Alembic commands ###
