"""ai impact resoning

Revision ID: b46a9f23de09
Revises: 4b1f3b27b247
Create Date: 2026-01-13 17:28:42.722062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46a9f23de09'
down_revision: Union[str, Sequence[str], None] = '4b1f3b27b247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_events', sa.Column('ai_impact_reasoning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_events', 'ai_impact_reasoning')
    # ### end Alembic commands ###
