"""decay cron

Revision ID: b7497238a6c2
Revises: 03883eeb1508
Create Date: 2026-01-15 23:34:13.429760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7497238a6c2'
down_revision: Union[str, Sequence[str], None] = '03883eeb1508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newspapers', sa.Column('home_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newspapers', 'home_url')
    # ### end Alembic commands ###
