"""last updated index

Revision ID: b97858db8177
Revises: b46a9f23de09
Create Date: 2026-01-15 00:08:21.534431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97858db8177'
down_revision: Union[str, Sequence[str], None] = 'b46a9f23de09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_events_last_updated_at'), 'news_events', ['last_updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_events_last_updated_at'), table_name='news_events')
    # ### end Alembic commands ###
