"""init

Revision ID: b9c65b7e7c0b
Revises: 
Create Date: 2026-01-06 11:57:08.602998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b9c65b7e7c0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('news_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structure: {"left": "markdown", "right": "markdown", "center": "markdown"}'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ENHANCED', 'PUBLISHED', 'ARCHIVED', name='eventstatus'), nullable=False),
    sa.Column('fe_priority', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('bias_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stance_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_summarized_at', sa.DateTime(), nullable=False),
    sa.Column('articles_at_last_summary', sa.Integer(), nullable=False),
    sa.Column('embedding_centroid', Vector(dim=768), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('search_vector_ts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', search_text)", persisted=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_active_events_embedding', 'news_events', ['embedding_centroid'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_centroid': 'vector_cosine_ops'}, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_events_search_vector', 'news_events', ['search_vector_ts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_news_events_is_active'), 'news_events', ['is_active'], unique=False)
    op.create_index(op.f('ix_news_events_status'), 'news_events', ['status'], unique=False)
    op.create_index(op.f('ix_news_events_subtitle'), 'news_events', ['subtitle'], unique=False)
    op.create_index(op.f('ix_news_events_title'), 'news_events', ['title'], unique=False)
    op.create_table('newspapers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bias', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('stance_label', sa.String(), nullable=True),
    sa.Column('stance_reasoning', sa.Text(), nullable=True),
    sa.Column('main_topics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('entities', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('key_points', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('newspaper_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.id'], ),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_event_date', 'articles', ['event_id', 'published_date'], unique=False)
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('newspaper_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newspaper_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('blocklist', sa.Text(), nullable=True),
    sa.Column('allowed_sections', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_is_active'), 'feeds', ['is_active'], unique=False)
    op.create_index(op.f('ix_feeds_url'), 'feeds', ['url'], unique=True)
    op.create_table('article_authors',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'author_id')
    )
    op.create_table('article_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_contents_article_id'), 'article_contents', ['article_id'], unique=False)
    op.create_table('articles_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('estimated_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('queue_name', sa.Enum('FILTER', 'CLUSTER', name='articlesqueuename'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_articles_queue_id'), 'articles_queue', ['id'], unique=False)
    op.create_index(op.f('ix_articles_queue_queue_name'), 'articles_queue', ['queue_name'], unique=False)
    op.create_index(op.f('ix_articles_queue_status'), 'articles_queue', ['status'], unique=False)
    op.create_index('ix_queue_pending_fifo', 'articles_queue', ['updated_at', 'queue_name'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('merge_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_article_id', sa.UUID(), nullable=False),
    sa.Column('target_event_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['target_event_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_article_id', 'target_event_id', name='uq_merge_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merge_proposals')
    op.drop_index('ix_queue_pending_fifo', table_name='articles_queue', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_articles_queue_status'), table_name='articles_queue')
    op.drop_index(op.f('ix_articles_queue_queue_name'), table_name='articles_queue')
    op.drop_index(op.f('ix_articles_queue_id'), table_name='articles_queue')
    op.drop_table('articles_queue')
    op.drop_index(op.f('ix_article_contents_article_id'), table_name='article_contents')
    op.drop_table('article_contents')
    op.drop_table('article_authors')
    op.drop_index(op.f('ix_feeds_url'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_is_active'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_table('authors')
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.drop_index('ix_article_event_date', table_name='articles')
    op.drop_table('articles')
    op.drop_table('newspapers')
    op.drop_index(op.f('ix_news_events_title'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_subtitle'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_status'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_is_active'), table_name='news_events')
    op.drop_index('ix_events_search_vector', table_name='news_events', postgresql_using='gin')
    op.drop_index('ix_active_events_embedding', table_name='news_events', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_centroid': 'vector_cosine_ops'}, postgresql_where=sa.text('is_active = true'))
    op.drop_table('news_events')
    # ### end Alembic commands ###
