"""updated_at proposals

Revision ID: d73e9fb1dbcd
Revises: e401fdfd400c
Create Date: 2026-01-13 00:14:36.732366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73e9fb1dbcd'
down_revision: Union[str, Sequence[str], None] = 'e401fdfd400c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merge_proposals', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merge_proposals', 'updated_at')
    # ### end Alembic commands ###
