"""blind_spot

Revision ID: d8d3d5444428
Revises: b7497238a6c2
Create Date: 2026-01-16 00:52:20.464956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d3d5444428'
down_revision: Union[str, Sequence[str], None] = 'b7497238a6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_events', sa.Column('is_blind_spot', sa.Boolean(), nullable=True))
    op.add_column('news_events', sa.Column('blind_spot_side', sa.String(), nullable=True))
    op.create_index(op.f('ix_news_events_blind_spot_side'), 'news_events', ['blind_spot_side'], unique=False)
    op.create_index(op.f('ix_news_events_is_blind_spot'), 'news_events', ['is_blind_spot'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_events_is_blind_spot'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_blind_spot_side'), table_name='news_events')
    op.drop_column('news_events', 'blind_spot_side')
    op.drop_column('news_events', 'is_blind_spot')
    # ### end Alembic commands ###
