"""summary status

Revision ID: dde6d0bcb4ba
Revises: b9c65b7e7c0b
Create Date: 2026-01-06 15:47:17.678593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde6d0bcb4ba'
down_revision: Union[str, Sequence[str], None] = 'b9c65b7e7c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('queue_name', sa.Enum('ENHANCER', 'PUBLISHER', name='eventsqueuename'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_events_queue_id'), 'events_queue', ['id'], unique=False)
    op.create_index('ix_events_queue_pending_fifo', 'events_queue', ['updated_at', 'queue_name'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('ix_events_queue_queue_name'), 'events_queue', ['queue_name'], unique=False)
    op.create_index(op.f('ix_events_queue_status'), 'events_queue', ['status'], unique=False)
    op.add_column('articles', sa.Column('summary_date', sa.DateTime(), nullable=False))
    op.add_column('articles', sa.Column('summary_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False))
    op.create_index(op.f('ix_articles_summary_status'), 'articles', ['summary_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_summary_status'), table_name='articles')
    op.drop_column('articles', 'summary_status')
    op.drop_column('articles', 'summary_date')
    op.drop_index(op.f('ix_events_queue_status'), table_name='events_queue')
    op.drop_index(op.f('ix_events_queue_queue_name'), table_name='events_queue')
    op.drop_index('ix_events_queue_pending_fifo', table_name='events_queue', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_events_queue_id'), table_name='events_queue')
    op.drop_table('events_queue')
    # ### end Alembic commands ###
