"""agg

Revision ID: e401fdfd400c
Revises: a1ab85f828b9
Create Date: 2026-01-12 23:25:01.846179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e401fdfd400c'
down_revision: Union[str, Sequence[str], None] = 'a1ab85f828b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merge_proposals', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WAITING', 'APPROVED', 'REJECTED', name='jobstatus'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merge_proposals', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WAITING', 'APPROVED', 'REJECTED', name='jobstatus'),
               server_default=sa.text("'PENDING'::jobstatus"),
               existing_nullable=False)
    # ### end Alembic commands ###
