"""update hot_score

Revision ID: e41c73e0b705
Revises: d73e9fb1dbcd
Create Date: 2026-01-13 00:45:26.844130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e41c73e0b705'
down_revision: Union[str, Sequence[str], None] = 'd73e9fb1dbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Create the update function
    # Formula: Score = EditorialScore / (HoursElapsed + 2)^1.5
    op.execute("""
    CREATE OR REPLACE FUNCTION update_hot_scores() RETURNS void AS $$
    BEGIN
        UPDATE news_events
        SET hot_score = (
            COALESCE(editorial_score, 0) / 
            POWER(
                (EXTRACT(EPOCH FROM (NOW() - COALESCE(published_at, created_at))) / 3600) + 2, 
                1.5
            )
        )
        WHERE is_active = true;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # 2. Schedule the cron job (if pg_cron is available)
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
            PERFORM cron.unschedule('update_hot_scores_job');
            PERFORM cron.schedule('update_hot_scores_job', '*/15 * * * *', 'SELECT update_hot_scores()');
        END IF;
    END$$;
    """)





    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merge_proposals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
            PERFORM cron.unschedule('update_hot_scores_job');
        END IF;
    END$$;
    """)
    op.execute("DROP FUNCTION IF EXISTS update_hot_scores();")

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merge_proposals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
