"""init

Revision ID: 3c696b9a41b7
Revises:
Create Date: 2026-01-20 00:20:50.529718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
# revision identifiers, used by Alembic.
revision: str = '3c696b9a41b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
op.execute("CREATE EXTENSION IF NOT EXISTS vector")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_table'), 'audit_logs', ['target_table'], unique=False)
    op.create_table('news_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structure: {"left": "markdown", "right": "markdown", "center": "markdown"}'),
    sa.Column('interest_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('main_topic_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ownership_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ENHANCED', 'PUBLISHED', 'ARCHIVED', 'MERGED', name='eventstatus'), nullable=False),
    sa.Column('fe_priority', sa.Integer(), nullable=False),
    sa.Column('bias_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stance_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stance', sa.Float(), nullable=True),
    sa.Column('clickbait_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('article_counts_by_bias', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_summarized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('articles_at_last_summary', sa.Integer(), nullable=False),
    sa.Column('embedding_centroid', Vector(dim=768), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('search_vector_ts', postgresql.TSVECTOR(), sa.Computed("to_tsvector('portuguese', search_text)", persisted=True), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('hot_score', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blind_spot', sa.Boolean(), nullable=True),
    sa.Column('blind_spot_side', sa.String(), nullable=True),
    sa.Column('best_source_rank', sa.Integer(), nullable=True),
    sa.Column('first_article_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_article_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_impact_score', sa.Integer(), nullable=True),
    sa.Column('ai_impact_reasoning', sa.String(), nullable=True),
    sa.Column('category_tag', sa.String(), nullable=True),
    sa.Column('is_international', sa.Boolean(), nullable=False),
    sa.Column('publisher_insights', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('sources_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('editorial_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_active_events_embedding', 'news_events', ['embedding_centroid'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_centroid': 'vector_cosine_ops'}, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_events_search_vector', 'news_events', ['search_vector_ts'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_news_events_article_count'), 'news_events', ['article_count'], unique=False)
    op.create_index(op.f('ix_news_events_blind_spot_side'), 'news_events', ['blind_spot_side'], unique=False)
    op.create_index(op.f('ix_news_events_hot_score'), 'news_events', ['hot_score'], unique=False)
    op.create_index(op.f('ix_news_events_is_active'), 'news_events', ['is_active'], unique=False)
    op.create_index(op.f('ix_news_events_is_blind_spot'), 'news_events', ['is_blind_spot'], unique=False)
    op.create_index(op.f('ix_news_events_is_international'), 'news_events', ['is_international'], unique=False)
    op.create_index(op.f('ix_news_events_last_updated_at'), 'news_events', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_news_events_published_at'), 'news_events', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_events_status'), 'news_events', ['status'], unique=False)
    op.create_index(op.f('ix_news_events_subtitle'), 'news_events', ['subtitle'], unique=False)
    op.create_index(op.f('ix_news_events_title'), 'news_events', ['title'], unique=False)
    op.create_table('newspapers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('home_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bias', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.Column('ownership_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WAITING', 'APPROVED', 'REJECTED', name='jobstatus'), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('stance', sa.Float(), nullable=True),
    sa.Column('stance_reasoning', sa.Text(), nullable=True),
    sa.Column('clickbait_score', sa.Float(), nullable=True),
    sa.Column('clickbait_reasoning', sa.Text(), nullable=True),
    sa.Column('main_topics', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('entities', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_points', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('embedding', Vector(dim=768), nullable=True),
    sa.Column('newspaper_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.id'], ),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_event_date', 'articles', ['event_id', 'published_date'], unique=False)
    op.create_index(op.f('ix_articles_summary_status'), 'articles', ['summary_status'], unique=False)
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('newspaper_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WAITING', 'APPROVED', 'REJECTED', name='jobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('queue_name', sa.Enum('ENHANCER', 'PUBLISHER', name='eventsqueuename'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_queue_id'), 'events_queue', ['id'], unique=False)
    op.create_index('ix_events_queue_pending_fifo', 'events_queue', ['updated_at', 'queue_name'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_index(op.f('ix_events_queue_queue_name'), 'events_queue', ['queue_name'], unique=False)
    op.create_index(op.f('ix_events_queue_status'), 'events_queue', ['status'], unique=False)
    op.create_table('feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('newspaper_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('blocklist', sa.Text(), nullable=True),
    sa.Column('allowed_sections', sa.Text(), nullable=True),
    sa.Column('url_pattern', sa.Text(), nullable=True),
    sa.Column('feed_type', sa.String(), server_default='sitemap', nullable=False),
    sa.Column('is_ranked', sa.Boolean(), nullable=False),
    sa.Column('use_browser_render', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('scroll_depth', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['newspaper_id'], ['newspapers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feeds_is_active'), 'feeds', ['is_active'], unique=False)
    op.create_index(op.f('ix_feeds_url'), 'feeds', ['url'], unique=True)
    op.create_table('article_authors',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'author_id')
    )
    op.create_table('articles_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WAITING', 'APPROVED', 'REJECTED', name='jobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('msg', sa.Text(), nullable=True),
    sa.Column('queue_name', sa.Enum('FILTER', 'ENRICHER', 'CLUSTER', 'ANALYZER', name='articlesqueuename'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_queue_id'), 'articles_queue', ['id'], unique=False)
    op.create_index(op.f('ix_articles_queue_queue_name'), 'articles_queue', ['queue_name'], unique=False)
    op.create_index(op.f('ix_articles_queue_status'), 'articles_queue', ['status'], unique=False)
    op.create_index('ix_queue_pending_fifo', 'articles_queue', ['updated_at', 'queue_name'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('merge_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.String(), nullable=False),
    sa.Column('source_article_id', sa.UUID(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('target_event_id', sa.UUID(), nullable=False),
    sa.Column('distance_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'WAITING', 'APPROVED', 'REJECTED', name='jobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['news_events.id'], ),
    sa.ForeignKeyConstraint(['target_event_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_article_id', 'target_event_id', name='uq_article_merge_pair'),
    sa.UniqueConstraint('source_event_id', 'target_event_id', name='uq_event_merge_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merge_proposals')
    op.drop_index('ix_queue_pending_fifo', table_name='articles_queue', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_articles_queue_status'), table_name='articles_queue')
    op.drop_index(op.f('ix_articles_queue_queue_name'), table_name='articles_queue')
    op.drop_index(op.f('ix_articles_queue_id'), table_name='articles_queue')
    op.drop_table('articles_queue')
    op.drop_table('article_authors')
    op.drop_index(op.f('ix_feeds_url'), table_name='feeds')
    op.drop_index(op.f('ix_feeds_is_active'), table_name='feeds')
    op.drop_table('feeds')
    op.drop_index(op.f('ix_events_queue_status'), table_name='events_queue')
    op.drop_index(op.f('ix_events_queue_queue_name'), table_name='events_queue')
    op.drop_index('ix_events_queue_pending_fifo', table_name='events_queue', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_events_queue_id'), table_name='events_queue')
    op.drop_table('events_queue')
    op.drop_table('authors')
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_summary_status'), table_name='articles')
    op.drop_index('ix_article_event_date', table_name='articles')
    op.drop_table('articles')
    op.drop_table('newspapers')
    op.drop_index(op.f('ix_news_events_title'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_subtitle'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_status'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_published_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_last_updated_at'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_is_international'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_is_blind_spot'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_is_active'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_hot_score'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_blind_spot_side'), table_name='news_events')
    op.drop_index(op.f('ix_news_events_article_count'), table_name='news_events')
    op.drop_index('ix_events_search_vector', table_name='news_events', postgresql_using='gin')
    op.drop_index('ix_active_events_embedding', table_name='news_events', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_centroid': 'vector_cosine_ops'}, postgresql_where=sa.text('is_active = true'))
    op.drop_table('news_events')
    op.drop_index(op.f('ix_audit_logs_target_table'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
