"""fix typo

Revision ID: 9daae42bb19a
Revises: 3c696b9a41b7
Create Date: 2026-01-21 22:05:10.531912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9daae42bb19a'
down_revision: Union[str, Sequence[str], None] = '3c696b9a41b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_events', 'publisher_isights', new_column_name='publisher_insights', existing_type=postgresql.ARRAY(sa.Text()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_events', 'publisher_insights', new_column_name='publisher_isights', existing_type=postgresql.ARRAY(sa.Text()))
    # ### end Alembic commands ###
